#define SCREEN_WIDTH  640
#define SCREEN_HEIGHT 480
#define KEY_REPEAT      1
#define DIR_LEFT        1
#define DIR_RIGHT       2
#define MISSILE_WIDTH    8
#define MISSILE_HEIGHT  16
#define FPS            30
#define ALIEN_GAP_X    20
#define ALIEN_GAP_Y    0
